config/routes.rb
Rails.application.routes.draw do

  resources :bookings, only: [:index, :show, :new, :create, :destroy]

  get '/rooms/real_state', to: 'rooms#real_state'
  get '/rooms/empty_with_booking', to: 'rooms#empty_with_booking'
  get '/rooms/busy_without_booking', to: 'rooms#busy_without_booking'

  resources :rooms
  resources :buildings
  resources :users

  get '/stats/top_five', to: 'stats#top_five'
  get '/stats/averages', to: 'stats#averages'
  get '/stats/rooms_bookings_by_day', to: 'stats#rooms_bookings_by_day'
  get '/stats/rooms_bookings_by_hour', to: 'stats#rooms_bookings_by_hour'

  root 'static_pages#home'
  get '/about', to: 'static_pages#about'

  get '/signup', to: 'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if !logged_in?
      redirect_to login_path
    elsif current_user.is_admin?
      @cant_admin = User.is_admin.count
      @cant_users = User.is_user.count
      @total_users = @cant_admin + @cant_users

      @cant_buildings = Building.count
      @rooms_per_building = Room.active.joins(:building).group("buildings.name").count

      @cant_rooms_active = Room.active.count
      @cant_rooms_inactive = Room.inactive.count
      @total_rooms = @cant_rooms_active + @cant_rooms_inactive

      @cant_bookings_past = Booking.where("valid_from < ?", DateTime.now).count
      @cant_bookings_next = Booking.where("valid_from > ?", DateTime.now).count
      @total_bookings = @cant_bookings_past + @cant_bookings_next
    else
      max_results = 5

      @bookings_today = current_user.bookings.where(valid_from: DateTime.now..DateTime.now.end_of_day).order("valid_from, valid_to").limit(max_results)
      @bookings_lasts = current_user.bookings.where("valid_from < ?", DateTime.now).order("valid_from DESC, valid_to DESC").limit(max_results)
      @bookings_nexts = current_user.bookings.where("valid_from > ?", DateTime.tomorrow.beginning_of_day).order("valid_from, valid_to").limit(max_results)
      @most_booked_rooms = current_user.rooms.group("rooms.id").order("count_all DESC").limit(max_results).count
    end
  end

  def about
  end
end

app/views/static_pages/_action_buttons.html.erb
<%= content_tag :div, class: "row justify-content-md-center text-center mt-4" do %>
<% if view_path != "" %>
<%= content_tag :div, class: "col mt-1" do %>
<%= link_to icon('fas', 'eye', class: 'mr-2') + 'View all', view_path, :class => "btn btn-outline-secondary btn-block btn-sm"%>
<% end %>
<% end %>
<% if new_path != "" %>
<%= content_tag :div, class: "col mt-1" do %>
<%= link_to icon('fas', 'plus', class: 'mr-2') + 'Add ' + create_text, new_path, :class => "btn btn-outline-success btn-block btn-sm"%>
<% end %>
<% end %>
<% end %>

app/views/static_pages/_home_admin.html.erb
<%= content_tag :div, class: "row justify-content-md-center text-center home_admin" do %>

<%= content_tag :div, class: "col-sm-3 mt-1" do %>
<%= content_tag :div, class: "card" do %>
<%= content_tag :h5, class: "card-header" do %>
Users
<% end %>
<%= content_tag :div, class: "card-body centered" do %>
<% view_path = users_path %>
<% if (@total_users) > 0 %>
Created users: <br />
<b><%= @total_users %></b>
<%= pie_chart({"User's" => @cant_users, "Admin's" => @cant_admin}, height: "280px", legend: "bottom", colors: ["#008B8B", "#20B2AA"]) %>
<% else %>
<% view_path = "" %>
<%= render partial: "alert_box", locals: {message_type: "info", message: "No users yet.", hide_alert: false} %>
<% end %>
<%= render partial: "action_buttons", locals: {create_text: 'user', view_path: view_path, new_path: new_user_path} %>
<% end %>
<% end %>
<% end %>

<%= content_tag :div, class: "col-sm-3 mt-1" do %>
<%= content_tag :div, class: "card" do %>
<%= content_tag :h5, class: "card-header" do %>
Rooms by site
<% end %>
<%= content_tag :div, class: "card-body centered" do %>
<% view_path = buildings_path %>
<% if (@cant_buildings) > 0 %>
Created sites: <br />
<b><%= @cant_buildings %></b>
<%= pie_chart(@rooms_per_building, height: "280px", legend: "bottom", suffix: " active rooms", colors: ["#483D8B", "#7B68EE", "#800080", "#8A2BE2", "#9932CC"]) %>
<% else %>
<% view_path = "" %>
<%= render partial: "alert_box", locals: {message_type: "info", message: "No sites yet.", hide_alert: false} %>
<% end %>
<%= render partial: "action_buttons", locals: {create_text: 'site', view_path: view_path, new_path: new_building_path} %>
<% end %>
<% end %>
<% end %>

<%= content_tag :div, class: "col-sm-3 mt-1" do %>
<%= content_tag :div, class: "card" do %>
<%= content_tag :h5, class: "card-header" do %>
Room's state
<% end %>
<%= content_tag :div, class: "card-body centered" do %>
<% view_path = rooms_path %>
<% if (@total_rooms) > 0 %>
Created rooms: <br />
<b><%= @total_rooms %></b>
<%= pie_chart({"Active" => @cant_rooms_active, "Inactive" => @cant_rooms_inactive}, height: "280px", legend: "bottom", colors: ["#FFA500", "#FF7F50"]) %>
<% else %>
<% view_path = "" %>
<%= render partial: "alert_box", locals: {message_type: "info", message: "No rooms yet.", hide_alert: false} %>
<% end %>
<%= render partial: "action_buttons", locals: {create_text: 'room', view_path: view_path, new_path: new_room_path} %>
<% end %>
<% end %>
<% end %>

<%= content_tag :div, class: "col-sm-3 mt-1" do %>
<%= content_tag :div, class: "card" do %>
<%= content_tag :h5, class: "card-header" do %>
Bookings
<% end %>
<%= content_tag :div, class: "card-body centered" do %>
<% view_path = bookings_path %>
<% if (@total_bookings) > 0 %>
Created bookings: <br />
<b><%= @total_bookings %></b>
<%= pie_chart({"Past" => @cant_bookings_past, "Next" => @cant_bookings_next}, height: "280px", legend: "bottom", colors: ["#8B0000", "#DC143C"]) %>
<% else %>
<% view_path = "" %>
<%= render partial: "alert_box", locals: {message_type: "info", message: "No bookings yet.", hide_alert: false} %>
<% end %>
<%= render partial: "action_buttons", locals: {create_text: 'booking', view_path: view_path, new_path: rooms_path} %>
<% end %>
<% end %>
<% end %>

<% end %>

app/views/static_pages/_home_user.html.erb
<%= content_tag :div, class: "row justify-content-md-center home_user" do %>

<%= content_tag :div, class: "col-sm-3 mt-1" do %>
<%= content_tag :div, class: "card" do %>
<%= content_tag :h5, class: "card-header" do %>
My last bookings
<% end %>
<%= content_tag :div, class: "card-body centered d-flex flex-column" do %>
<% if @bookings_lasts.count > 0 %>
<%= content_tag :ul, class: "fa-ul" do %>
<% @bookings_lasts.each do |b| %>
<%= content_tag :li do %>
<%= content_tag :span, class: "fa-li text-secondary" do %>
<%= icon('fas', 'arrow-circle-left') %>
<% end %>
<b><%= b.room.name %></b>
<br />
(<%= b.valid_from.strftime('%d/%m/%Y %H:%M') %> - <%= b.valid_to.strftime('%H:%M') %>)
<% end %>
<% end %>
<% end %>
<% else %>
<%= render partial: "alert_box", locals: {message_type: "info", message: "No bookings.", hide_alert: false} %>
<% end %>
<%= link_to icon('fas', 'book-open', class: 'mr-2') + 'View all my bookings', bookings_path, :class => "btn btn-outline-secondary btn-block btn-sm mt-auto"%>
<% end %>
<% end %>
<% end %>

<%= content_tag :div, class: "col-sm-3 mt-1" do %>
<%= content_tag :div, class: "card" do %>
<%= content_tag :h5, class: "card-header" do %>
My today's bookings
<% end %>
<%= content_tag :div, class: "card-body centered d-flex flex-column" do %>
<% if @bookings_today.count > 0 %>
<%= content_tag :ul, class: "fa-ul" do %>
<% @bookings_today.each do |b| %>
<%= content_tag :li do %>
<%= content_tag :span, class: "fa-li text-warning" do %>
<%= icon('fas', 'arrow-circle-down') %>
<% end %>
<b><%= b.room.name %></b>
&nbsp;
<%= link_to icon('fas', 'trash-alt', class: 'text-danger'), b, method: :delete, data: { confirm: 'Do you want to cancel this booking?' }, "data-toggle" => "tooltip", "data-original-title" => "Cancel booking", "data-placement" => "top" %>
<br />
(<%= b.valid_from.strftime('%d/%m/%Y %H:%M') %> - <%= b.valid_to.strftime('%H:%M') %>)
<% end %>
<% end %>
<% end %>
<% else %>
<%= render partial: "alert_box", locals: {message_type: "info", message: "No bookings.", hide_alert: false} %>
<% end %>
<%= link_to icon('fas', 'book-open', class: 'mr-2') + 'View all my bookings', bookings_path, :class => "btn btn-outline-secondary btn-block btn-sm mt-auto"%>
<% end %>
<% end %>
<% end %>

<%= content_tag :div, class: "col-sm-3 mt-1" do %>
<%= content_tag :div, class: "card" do %>
<%= content_tag :h5, class: "card-header" do %>
My next bookings
<% end %>
<%= content_tag :div, class: "card-body centered d-flex flex-column" do %>
<% if @bookings_nexts.count > 0 %>
<%= content_tag :ul, class: "fa-ul" do %>
<% @bookings_nexts.each do |b| %>
<%= content_tag :li do %>
<%= content_tag :span, class: "fa-li text-primary" do %>
<%= icon('fas', 'arrow-circle-right') %>
<% end %>
<b><%= b.room.name %></b>
&nbsp;
<%= link_to icon('fas', 'trash-alt', class: 'text-danger'), booking_path(b, home: 'true'), method: :delete, data: { confirm: 'Do you want to cancel this booking?' }, "data-toggle" => "tooltip", "data-original-title" => "Cancel booking", "data-placement" => "top" %>
<br />
(<%= b.valid_from.strftime('%d/%m/%Y %H:%M') %> - <%= b.valid_to.strftime('%H:%M') %>)
<% end %>
<% end %>
<% end %>
<% else %>
<%= render partial: "alert_box", locals: {message_type: "info", message: "No bookings.", hide_alert: false} %>
<% end %>
<%= link_to icon('fas', 'book-open', class: 'mr-2') + 'View all my bookings', bookings_path, :class => "btn btn-outline-secondary btn-block btn-sm mt-auto"%>
<% end %>
<% end %>
<% end %>

<%= content_tag :div, class: "col-sm-3 mt-1" do %>
<%= content_tag :div, class: "card" do %>
<%= content_tag :h5, class: "card-header" do %>
My most booked rooms
<% end %>
<%= content_tag :div, class: "card-body centered d-flex flex-column" do %>
<% if @most_booked_rooms.count > 0 %>
<table class="w-100 m-0">
  <% @most_booked_rooms.each do |r| %>
  <tr>
    <td style="width: 30px;">
      <%= icon('fas', 'check-circle', class: "text-success") %>
    </td>
    <td>
      <b><%= Room.find(r[0]).name %></b>
    </td>
    <td rowspan="2" style="width: 120px;">
      <%= link_to icon('fas', 'book-open', class: 'mr-2') + 'Book now', new_booking_path(room_id: r[0]), :class => "btn btn-outline-success btn-sm"%>
    </td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>
      (<%= r[1] %> booking<% if r[1] > 1 %>s<% end %>)
    </td>
  </tr>
  <% end %>
</table>
<br />
<% else %>
<%= render partial: "alert_box", locals: {message_type: "info", message: "No rooms.", hide_alert: false} %>
<% end %>
<%= link_to icon('fas', 'door-open', class: 'mr-2') + 'View all rooms', rooms_path, :class => "btn btn-outline-secondary btn-block btn-sm mt-auto"%>
<% end %>
<% end %>
<% end %>

<% end %>

<style>
  span {
    padding-right: 20px;
  }
</style>

<script>
  var max_height = 250;

  $('.card-body').each(function (i, obj) {
    if ($(this).height() > max_height) {
      max_height = $(this).height();
    }
  });
  $('.card-body').each(function (i, obj) {
    $(this).height(max_height + 20);
  });
</script>

app/views/static_pages/about.html.erb
<div class="card">
  <h5 class="card-header">Smarter Rooms v1.0 developed by:</h5>
  <div class="card-body centered">
    <table>
      <td width="250px">
        <%= image_tag("/riverosm.jpg", alt: "Matias Riveros Profile Image") %>
      </td>
      <td>
        <p class="mt-3"><b>Matias Riveros</b></p>
        <p class="mt-3">+5411 5286-5943</p>
        <p>IBM Martinez - Buenos Aires - Argentina</p>
        <p><a href="mailto: riverosm@ar.ibm.com?Subject=CodeAcademyL3" target="_blank"
            title="Email me!">riverosm@ar.ibm.com</a></p>
      </td>
    </table>
  </div>
</div>

app/views/static_pages/home.html.erb
<% if logged_in? %>
<% if current_user.is_admin? %>
<%= render partial: "home_admin" %>
<% else %>
<%= render partial: "home_user" %>
<% end %>

<% else %>
<%= link_to "Log in", login_path %>
<% end %>