config/routes.rb
Rails.application.routes.draw do

  resources :bookings, only: [:index, :show, :new, :create, :destroy]

  get '/rooms/real_state', to: 'rooms#real_state'
  get '/rooms/empty_with_booking', to: 'rooms#empty_with_booking'
  get '/rooms/busy_without_booking', to: 'rooms#busy_without_booking'

  resources :rooms
  resources :buildings
  resources :users

  get '/stats/top_five', to: 'stats#top_five'
  get '/stats/averages', to: 'stats#averages'
  get '/stats/rooms_bookings_by_day', to: 'stats#rooms_bookings_by_day'
  get '/stats/rooms_bookings_by_hour', to: 'stats#rooms_bookings_by_hour'

  root 'static_pages#home'
  get '/about', to: 'static_pages#about'

  get '/signup', to: 'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/building.rb
class Building < ApplicationRecord
  validates :name, presence: true, length: { maximum: 90 }, uniqueness: true

  has_many :rooms

  def get_active_rooms_count
    self.rooms.active.count
  end

  def get_inactive_rooms_count
    self.rooms.inactive.count
  end

  def get_map_image_tag
    # external seeding => id unknown so I'll try by name ...
    building_map_image = "/ibm_logo_200.png"

    if self.name.downcase.include?("martinez") || self.name.downcase.include?("martínez")
      building_map_image = "/sites/ibm_martinez_map.png"
    elsif self.name.downcase.include?("catalinas")
      building_map_image = "/sites/ibm_catalinas_map.png"
    end

    path = Rails.root.join("public/sites/#{self.id}.jpg")

    ActionController::Base.helpers.image_tag(building_map_image, {
        class: "building_image rounded", size: "200", "data-toggle" => "tooltip",
        "data-original-title" => "LatLng: " + self.latitude.to_s + ", " + self.longitude.to_s, "data-placement" => "right"})
  end

  def get_building_image_tag
    building_image = "/ibm_logo.png"

    # external seeding => id unknown so I'll try by name ...
    if self.name.downcase.include?("martinez") || self.name.downcase.include?("martínez")
      building_image = "/sites/ibm_martinez.jpg"
    elsif self.name.downcase.include?("catalinas")
      building_image = "/sites/ibm_catalinas.jpg"
    end

    # if we know the id
    #path = Rails.root.join("public/sites/#{self.id}.jpg")
    #if File.exists?(path)
    #  building_image = "/sites/#{self.id}.jpg"
    #end
    ActionController::Base.helpers.image_tag(building_image, class: "building_image")
  end
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  before_action :set_building, only: [:show, :edit, :update, :destroy]

  before_action :verify_if_admin_and_redirect_with_error_message_if_not, only: [:show, :edit, :update, :destroy, :new, :create]

  # GET /buildings
  # GET /buildings.json
  def index
    @buildings = Building.all
  end

  # GET /buildings/1
  # GET /buildings/1.json
  def show
    redirect_to buildings_path
  end

  # GET /buildings/new
  def new
    @building = Building.new
  end

  # GET /buildings/1/edit
  def edit
  end

  # POST /buildings
  # POST /buildings.json
  def create
    @building = Building.new(building_params)

    respond_to do |format|
      if @building.save
        flash[:success] = "Site was successfully created."
        format.html { redirect_to @building }
        format.json { render :show, status: :created, location: @building }
      else
        error_msgs = ""
        @building.errors.full_messages.each do |msg|
            error_msgs = "<li>#{msg}</li>"
        end
        flash.now[:danger] = "There was #{@building.errors.count.to_s} error(s): <br /> <ul>#{error_msgs}</ul>"
        format.html { render :new }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buildings/1
  # PATCH/PUT /buildings/1.json
  def update
    respond_to do |format|
      if @building.update(building_params)
        flash[:success] = "Site was successfully updated."
        format.html { redirect_to @building }
        format.json { render :show, status: :ok, location: @building }
      else
        error_msgs = ""
        @building.errors.full_messages.each do |msg|
            error_msgs = "<li>#{msg}</li>"
        end
        flash.now[:danger] = "There was #{@building.errors.count.to_s} error(s): <br /> <ul>#{error_msgs}</ul>"
        format.html { render :edit }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buildings/1
  # DELETE /buildings/1.json
  def destroy
    # Remove for enable delete
    #@building.destroy
    #respond_to do |format|
    #  flash.now[:success] = "Site was successfully destroyed."
    #  format.html { redirect_to buildings_url }
    #  format.json { head :no_content }
    #end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_building
      @building = Building.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def building_params
      params.require(:building).permit(:name, :address, :latitude, :longitude)
    end
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/views/buildings/_form.html.erb
<%= form_with model: @building, local: true, class: "forms" do |f| %>

<%= render partial: "form_label", locals: {required: true, field: :name,  fa_icon: 'building',
                                           placeholder: 'Name', type: 'text', form: f} %>

<%= render partial: "form_label", locals: {required: true, field: :address,  fa_icon: 'map-pin',
                                           placeholder: 'Address', type: 'text', form: f} %>

<%= render partial: "form_label", locals: {required: true, field: :latitude,  fa_icon: 'compass',
                                           placeholder: 'Latitude', type: 'float', form: f} %>

<%= render partial: "form_label", locals: {required: true, field: :longitude,  fa_icon: 'compass',
                                           placeholder: 'Longitude', type: 'float', form: f} %>

<%= content_tag :div, class: "input-group mb-3 row" do %>
<%= content_tag :div, class: "col" do %>
<%= link_to 'Back', buildings_path, :class => "btn btn-outline-secondary btn-block"%>
<% end %>
<%= content_tag :div, class: "col" do %>
<% if action == "new" %>
<%= f.submit :"Create site", class: "btn-outline-success btn btn-block" %>
<% else %>
<%= f.submit :"Save", class: "btn-outline-warning btn btn-block" %>
<% end %>
<% end %>
<% end %>

<% end %>

app/views/buildings/edit.html.erb
<h3>Editing site</h3>

<%= render 'form', building: @building, action: 'edit' %>

app/views/buildings/index.html.erb
<h3>Sites</h3>

<% if @buildings.size == 0 %>

<%= render partial: "alert_box", locals: {message_type: "info", message: "No sites yet.", hide_alert: false} %>

<% end %>

<% i = 0 %>
<% @buildings.each do |building| 
if (i % 4) == 0 %>
<div class="row justify-content-md-center text-center buildings">
  <% end %>
  <div class="col-sm-3 mt-1">
    <div class="card">
      <h5 class="card-header"><b><%= building.name %></b></h5>
      <div class="card-body centered">
        <a href="<%=rooms_path(:building => building.id)%>">
          <div class="row mb-3">
            <div class="col"><%= building.address %></div>
          </div>
          <div class="row mb-3">
            <div class="col"><%= building.get_map_image_tag %></div>
          </div>
          <% if current_user.is_admin? %>
          <div class="row mb-3">
            <div class="col">Active rooms: <b><%= building.get_active_rooms_count %></b></div>
          </div>
          <div class="row mb-3">
            <div class="col">Inactive rooms: <b><%= building.get_inactive_rooms_count %></b></div>
          </div>
          <div class="row mb-3">
            <div class="col">
              <%= link_to rooms_path(:building => building.id) do %>
              <%= icon('fas', 'door-open', class: "text-primary", "data-toggle" => "tooltip", "data-original-title" => "View rooms", "data-placement" => "top") %>
              <% end %>
            </div>
            <div class="col">
              <%= link_to new_room_path(building_id: building.id) do %>
              <%= icon('fas', 'plus', class: "text-success", "data-toggle" => "tooltip", "data-original-title" => "Create new room", "data-placement" => "top") %>
              <% end %>
            </div>
            <div class="col">
              <%= link_to edit_building_path(building) do %>
              <%= icon('fas', 'edit', class: "text-warning", "data-toggle" => "tooltip", "data-original-title" => "Edit building", "data-placement" => "top") %>
              <% end %>
            </div>
            <!-- Remove for enable delete
          <div class="col">
            <%= link_to building, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <%= icon('fas', 'trash-alt', class: "text-danger", "data-toggle" => "tooltip", "data-original-title" => "Delete building", "data-placement" => "top") %>
            <% end %>
          </div>
            //-->
          </div>
          <% else %>
          <div class="row mb-3">
            <div class="col">
              <%= link_to rooms_path(:building => building.id) do %>
              <%= icon('fas', 'search', class: "fa-3x text-primary", "data-toggle" => "tooltip", "data-original-title" => "Find rooms (" + building.rooms.size.to_s + ")", "data-placement" => "top") %>
              <% end %>
            </div>
          </div>
          <% end %>
        </a>
      </div>
    </div>
  </div>

  <% i = i + 1 %>
  <%if (i % 4) == 0 || i == @buildings.size %>
</div>
<% end %>
<% end %>

<% if current_user.is_admin? %>

<div class="row mt-4 justify-content-md-center text-center">
  <div class="col-sm-3 m-1">
    <%= link_to 'Back', root_path, :class => "btn btn-outline-secondary btn-block"%>
  </div>
  <div class="col-sm-3 m-1">
    <%= link_to 'Create new site', new_building_path, :class => "btn btn-outline-success btn-block"%>
  </div>
</div>

<% else %>

<div class="row mt-4 justify-content-md-center text-center">
  <div class="col-sm-3 m-1">
    <%= link_to 'View all rooms', rooms_path, :class => "btn btn-outline-primary btn-block"%>
  </div>
</div>

<% end %>

app/views/buildings/new.html.erb
<h3>Add site</h3>

<%= render 'form', building: @building, action: 'new' %>