config/routes.rb
Rails.application.routes.draw do

  resources :bookings, only: [:index, :show, :new, :create, :destroy]

  get '/rooms/real_state', to: 'rooms#real_state'
  get '/rooms/empty_with_booking', to: 'rooms#empty_with_booking'
  get '/rooms/busy_without_booking', to: 'rooms#busy_without_booking'

  resources :rooms
  resources :buildings
  resources :users

  get '/stats/top_five', to: 'stats#top_five'
  get '/stats/averages', to: 'stats#averages'
  get '/stats/rooms_bookings_by_day', to: 'stats#rooms_bookings_by_day'
  get '/stats/rooms_bookings_by_hour', to: 'stats#rooms_bookings_by_hour'

  root 'static_pages#home'
  get '/about', to: 'static_pages#about'

  get '/signup', to: 'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/room.rb
class Room < ApplicationRecord
  validates :name, presence: true, length: { maximum: 90 }
  validates :code, presence: true, uniqueness: true

  belongs_to :building
  has_many :room_accesories
  has_many :accesories, through: :room_accesories

  scope :active, -> {where("active = 1")}
  scope :inactive, -> {where("active = 0")}

  has_many :bookings
  has_many :users, through: :bookings

  paginates_per Rails.configuration.smarter_rooms_rooms_per_page

  def get_bookings (user)
    room_bookings = []
    self.bookings.each do |b|
      room_booking = Hash.new

      if user.is_admin?
        room_booking["id"] = b.id
        room_booking["title"] = b.user.name
        room_booking["backgroundColor"] = "#ADD8E6"
        room_booking["textColor"] = "#000000"
        room_booking["extendedProps"] = Hash.new
        room_booking["extendedProps"]["icon"] = "user-clock"
      else
        if (user == b.user)
          room_booking["title"] = "Your's booking"
          room_booking["backgroundColor"] = "#ADD8E6"
          room_booking["borderColor"] = "#000"
          room_booking["extendedProps"] = Hash.new
          room_booking["extendedProps"]["can_delete"] = b.id
        else
          room_booking["title"] = "Another's booking"
          room_booking["backgroundColor"] = "#CCC"
          room_booking["borderColor"] = "#CCC"
        end
      end
      room_booking["start"] = b.valid_from
      room_booking["end"] = b.valid_to
      room_bookings << room_booking
    end
    room_bookings
  end

  def get_room_accesories_count
    room_accesories_count = []
    Accesory.all.each do |a|
      room_accesories = Hash.new
      room_accesories["name"] = a.name
      room_accesories["quantity"] = self.accesory_count(a)
      if a.icon.nil? || a.icon == ""
        # set default icon if no icon present
        room_accesories["icon"] = "laptop"
      else
        room_accesories["icon"] = a.icon
      end

      room_accesories["class"] = ""
      room_accesories["class"] = "accesory_disabled" if room_accesories["quantity"] == 0
      room_accesories["quantity"] = "No " if room_accesories["quantity"] == 0
      room_accesories_count << room_accesories
    end
    room_accesories_count
  end

  def accesory_count (accesory)
    has_accesory = self.room_accesories.where(accesory: accesory).first
    if has_accesory != nil
      has_accesory.quantity
    else
      0
    end
  end

  def get_estimated_occupants
    # get_estimated_occupants returns:
    #   nil -> room was not found by code
    #   0 -> room is free
    #   # -> estimated occupants

    room_api_full_url = Rails.configuration.smarter_rooms_rooms_api_url + Rails.configuration.smarter_rooms_rooms_api_path + code
    @response = Faraday.get room_api_full_url
    if (@response.status != 200)
      nil
    else
      JSON.parse(@response.body)["estimated_occupants"]
    end
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  before_action :verify_if_admin_and_redirect_with_error_message_if_not, only: [:new, :edit, :update, :destroy, :real_state, :busy_without_booking, :empty_with_booking]

  # GET /rooms
  # GET /rooms.json
  def index
    @title = "All rooms"
    if @current_user.is_admin?
      @rooms = Room.all
    else
      @rooms = Room.active
    end

    if (params["search_name"] != nil && params["search_name"] != "")
      @title = "Rooms search results"
      @rooms = @rooms.where("name like ?", "%#{params["search_name"]}%")
    elsif (params["building"] != nil && params["building"] != "")
      building = Building.find(params[:building])
      @rooms = @rooms.where(building: building)
      @title = building.name + " rooms"
    end

    @rooms = @rooms.order(:name).page params[:pagina]
  end

  # GET /rooms/empty_with_booking
  # GET /rooms/empty_with_booking.json
  def empty_with_booking
    respond_to do |format|
      format.html { render :empty_with_booking }
      format.json {
        @rooms = []
        booked_now_rooms = Booking.booked_now.map{|booked_now| booked_now.room}
        if booked_now_rooms == []
          booked_now_rooms = ''
        end
        Room.where("id IN (?)", booked_now_rooms).each do |booked_room|
          room_info = Hash.new
          room_info["estimated_occupants"] = booked_room.get_estimated_occupants

          if !room_info["estimated_occupants"].nil? && room_info["estimated_occupants"] == 0
            room_info["name"] = booked_room.name
            room_info["building"] = booked_room.building.name
            room_info["max_capacity"] = booked_room.max_capacity
            room_info["state"] = "Empty with active booking!"
            room_info["class"] = "danger"
            room_info["used_percent"] = (room_info["estimated_occupants"].to_f / room_info["max_capacity"].to_f * 100).ceil
            @rooms << room_info
          end
        end
        render json: @rooms
      }
    end
  end

  # GET /rooms/real_state
  # GET /rooms/real_state.json
  def real_state
    respond_to do |format|
      format.html { render :real_state }
      format.json {
        @rooms = []
        Room.all.each do |r|
          room_info = Hash.new
          room_info["name"] = r.name
          room_info["building"] = r.building.name
          room_info["max_capacity"] = r.max_capacity
          room_info["estimated_occupants"] = r.get_estimated_occupants
          room_info["used_percent"] = 100

          if room_info["estimated_occupants"].nil?
            room_info["state"] = "No info!"
            room_info["class"] = "danger"
            room_info["used_percent"] = 0
            room_info["estimated_occupants"] = "Unknown"
          elsif room_info["estimated_occupants"] == 0
            room_info["state"] = "Empty room!"
            room_info["class"] = "success"
            room_info["used_percent"] = 0
          elsif room_info["max_capacity"] == room_info["estimated_occupants"]
            room_info["state"] = "Filled room!"
            room_info["class"] = "warning"
          elsif room_info["max_capacity"] > room_info["estimated_occupants"]
            room_info["state"] = "Busy room!"
            room_info["class"] = "primary"
            room_info["used_percent"] = (room_info["estimated_occupants"].to_f / room_info["max_capacity"].to_f * 100).ceil
          elsif room_info["max_capacity"] < room_info["estimated_occupants"]
            room_info["state"] = "Overfilled room!"
            room_info["class"] = "danger"
          end
          @rooms << room_info
        end
        render json: @rooms
      }
    end
  end

  # GET /rooms/busy_without_booking
  # GET /rooms/busy_without_booking.json
  def busy_without_booking
    respond_to do |format|
      format.html { render :busy_without_booking }
      format.json {
        @rooms = []
        booked_now_rooms = Booking.booked_now.map{|booked_now| booked_now.room}
        if booked_now_rooms == []
          booked_now_rooms = ''
        end
        Room.where("id NOT IN (?)", booked_now_rooms).each do |not_booked_room|
          room_info = Hash.new
          room_info["estimated_occupants"] = not_booked_room.get_estimated_occupants

          if !room_info["estimated_occupants"].nil? && room_info["estimated_occupants"] > 0
            room_info["name"] = not_booked_room.name
            room_info["building"] = not_booked_room.building.name
            room_info["max_capacity"] = not_booked_room.max_capacity
            room_info["state"] = "Busy without booking!"
            room_info["class"] = "danger"
            room_info["used_percent"] = (room_info["estimated_occupants"].to_f / room_info["max_capacity"].to_f * 100).ceil
            @rooms << room_info
          end
        end
        render json: @rooms 
      }
    end
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    if (!@room.active? && !current_user.is_admin?)
      flash[:danger] = "You are not allowed to access this room."
      redirect_to rooms_url
    else
      respond_to do |format|
        format.html { redirect_to rooms_path }
        room_info = Hash.new
        format.json {
          room_info["room_info"] = @room
          booking_info = Hash.new
          room_info["bookings"] = @room.get_bookings(current_user)
          if params["only_bookings"] == "1"
            render json: room_info["bookings"]
          else
            render json: room_info
          end
        }
      end
    end
  end

  # GET /rooms/new
  def new
    @room = Room.new
    @buildings = Building.all.sort_by{|b| b.name}
    @building_id = ""
    if !params[:building_id].nil?
      @building_id = params[:building_id]
    end
  end

  # GET /rooms/1/edit
  def edit
    @buildings = Building.all.sort_by{|b| b.name}
    @building_id = @room.building.id
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)
    @buildings = Building.all.sort_by{|b| b.name}

    respond_to do |format|
      if @room.save
        flash[:success] = "Room was successfully created."
        format.html { redirect_to rooms_path(building: room_params[:building_id]) }
        format.json { render :show, status: :created, location: @room }
      else
        error_msgs = ""
        @room.errors.full_messages.each do |msg|
            error_msgs = "<li>#{msg}</li>"
        end
        flash.now[:danger] = "There was #{@room.errors.count.to_s} error(s): <br /> <ul>#{error_msgs}</ul>"
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        flash[:success] = "Room was successfully updated."
        if (room_params.has_key?(:name))
          format.html { redirect_to rooms_path(building: room_params[:building_id]) }
          format.json { render :show, status: :ok, location: @room }
        else
          format.html { redirect_to rooms_path(building: room_params[:building_id]) }
        end
      else
        error_msgs = ""
        @room.errors.full_messages.each do |msg|
            error_msgs = "<li>#{msg}</li>"
        end
        flash.now[:danger] = "There was #{@room.errors.count.to_s} error(s): <br /> <ul>#{error_msgs}</ul>"
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    # Remove for enable delete
    #@room.destroy
    #respond_to do |format|
    #  flash[:success] = "Room was successfully destroyed."
    #  format.html { redirect_to rooms_url }
    #  format.json { head :no_content }
    #end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:name, :code, :floor, :max_capacity, :active, :building_id)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<% if @buildings.count > 0 %>

<%= form_with model: @room, local: true, class: "forms" do |f| %>

<%= render partial: "form_label", locals: {required: true, field: :name,  fa_icon: 'door-open',
                                           placeholder: 'Name', type: 'text', form: f} %>

<%= render partial: "form_label", locals: {required: true, field: :code,  fa_icon: 'map-pin',
                                           placeholder: 'Code', type: 'text', form: f} %>

<%= render partial: "form_label", locals: {required: true, field: :floor,  fa_icon: 'city',
                                           placeholder: 'Floor', type: 'number', form: f} %>

<%= render partial: "form_label", locals: {required: true, field: :max_capacity,  fa_icon: 'users',
                                           placeholder: 'Max capacity', type: 'number', form: f} %>

<%= content_tag :div, class: "input-group mb-3 row" do %>
<%= content_tag :div, class: "input-group-prepend" do %>
<%= content_tag :span, class: "input-group-text" do %>
<%= icon('fas', 'city', class: 'fa-fw') %>
<% end %>
<% end %>
<%= f.collection_select :building_id, @buildings, :id, :name, {:include_blank => 'All buildings', :selected => @building_id}, {class: "custom-select", required: true} %>
<% end %>

<%= content_tag :div, class: "input-group mb-3 row" do %>
<%= content_tag :div, class: "input-group-prepend" do %>
<%= content_tag :span, class: "input-group-text" do %>
<% if action == "new" %>
<%= f.check_box :active, {required: false, checked: true, class: "faw"} %> &nbsp;
<% else %>
<%= f.check_box :active, {required: false, class: "faw"} %> &nbsp;
<% end %>
<% end %>
<% end %>
<%= f.text_field "", :disabled => true, placeholder: "Activate room", class: "form-control", style: "background-color: white" %>
<% end %>

<%= content_tag :div, class: "input-group mb-3 row" do %>
<%= content_tag :div, class: "col" do %>
<% if @building_id == "" %>
<%= link_to 'Back', rooms_path, :class => "btn btn-outline-secondary btn-block"%>
<% else %>
<%= link_to 'Back', buildings_path, :class => "btn btn-outline-secondary btn-block"%>
<% end %>
<% end %>
<%= content_tag :div, class: "col" do %>
<% if action == "new" %>
<%= f.submit :"Create room", class: "btn-outline-success btn btn-block" %>
<% else %>
<%= f.submit :"Save", class: "btn-outline-warning btn btn-block" %>
<% end %>
<% end %>
<% end %>

<% end %>

<% else %>

<%= render partial: "alert_box", locals: {message_type: "info", message: "There are no sites yet.", hide_alert: false} %>

<% end %>

app/views/rooms/busy_without_booking.html.erb
<h3>Busy rooms without booking</h3>

<div id="div_info" style="display: none;"><i>The provided information is estimated.</i></div>

<div id="div_loading">
  <button class="btn btn-block btn-primary" type="button" disabled>
    Plase wait, collecting information from IoT ... <br />
    <span class="spinner-grow" style="width: 3rem; height: 3rem;" role="status" aria-hidden="true"></span>
    <br />Don't close this browser window ...
  </button>
</div>

<div class="row justify-content-md-center text-center" id="showData"></div>

<script>
  $.getJSON("/rooms/busy_without_booking.json").done(function (data) {
    var emptySet = true;
    $.each(data, function (key, room) {
      emptySet = false;
      var new_div = document.createElement("div");
      new_div.className = "col-sm-2 mt-1"
      new_div.innerHTML = '<div class="card text-center"><h5 class="card-header"><b>' + room.name + '</b></h5>' +
        '<div class="card-body centered">' +
        '<p>' + room.building + '</p>' +
        '<div class="progress" style="height: 15px;">' +
        '<div class="progress-bar bg-primary" role="progressbar" style="width: ' + room.used_percent + '%;" aria-valuenow="' + room.used_percent + '" aria-valuemin="0" aria-valuemax="100"></div>' +
        '</div>' +
        '<p>' + room.estimated_occupants + ' of ' + room.max_capacity + '</p>' +
        '<button class="btn btn-block btn-' + room.class + '" type="button" disabled>' +
        room.state +
        '</button>' +
        '</div>' +
        '</div>';
      $('#showData').append(new_div);
    })
    $('#div_loading').hide();
    if (emptySet) {
      $('#div_info').html('<p class="text-danger text-center">No available results</p>');
      $('#div_info').show();
    } else {
      $('#div_info').show();
    }
  });
</script>

app/views/rooms/edit.html.erb
<h3>Edit Room</h3>

<%= render 'form', room: @room, action: 'edit' %>

app/views/rooms/empty_with_booking.html.erb
<h3>Empty rooms with active booking</h3>

<div id="div_info" style="display: none;"><i>The provided information is estimated.</i></div>

<div id="div_loading">
  <button class="btn btn-block btn-primary" type="button" disabled>
    Plase wait, collecting information from IoT ... <br />
    <span class="spinner-grow" style="width: 3rem; height: 3rem;" role="status" aria-hidden="true"></span>
    <br />Don't close this browser window ...
  </button>
</div>

<div class="row justify-content-md-center text-center" id="showData"></div>

<script>
  $.getJSON("/rooms/empty_with_booking.json").done(function (data) {
    var emptySet = true;
    $.each(data, function (key, room) {
      emptySet = false;

      var new_div = document.createElement("div");
      new_div.className = "col-sm-2 mt-1"
      new_div.innerHTML = '<div class="card text-center"><h5 class="card-header"><b>' + room.name + '</b></h5>' +
        '<div class="card-body centered">' +
        '<p>' + room.building + '</p>' +
        '<div class="progress" style="height: 15px;">' +
        '<div class="progress-bar bg-primary" role="progressbar" style="width: ' + room.used_percent + '%;" aria-valuenow="' + room.used_percent + '" aria-valuemin="0" aria-valuemax="100"></div>' +
        '</div>' +
        '<p>' + room.estimated_occupants + ' of ' + room.max_capacity + '</p>' +
        '<button class="btn btn-block btn-' + room.class + '" type="button" disabled>' +
        room.state +
        '</button>' +
        '</div>' +
        '</div>';
      $('#showData').append(new_div);
    })
    $('#div_loading').hide();
    if (emptySet) {
      $('#div_info').html('<p class="text-danger text-center">No available results</p>');
      $('#div_info').show();
    } else {
      $('#div_info').show();
    }
  });
</script>

app/views/rooms/index.html.erb
<h3><%= @title %></h3>

<% if @rooms.size == 0 %>

<%= render partial: "alert_box", locals: {message_type: "info", message: "No rooms with selected criteria.", hide_alert: false} %>

<% end %>

<% i = 0 %>
<% @rooms.each do |room| 
if (i % Kaminari.config.default_per_page) == 0 %>
<div class="row justify-content-md-center">
  <% end %>
  <div class="col-sm-2 mt-1">
    <% if current_user.is_admin? %>
    <div class="card<%= room.active? ? ' border-success' : ' border-danger' %>">
      <div class="card-body centered">
        <% end %>
        <% if room.active? %>
        <a href="<%=new_booking_path(room_id: room.id)%>">
        <% end %>
          <div class="room_info bg-dark rounded">
            <span class="room_name"><b><%= room.name %></b></span> <br />
            <span class="room_name">Room</span>
            <hr />
            <span class="room_accesories"><%= icon('fas', 'users') %> <%= room.max_capacity %> people max.</span><br />
            <span class="room_accesories">
              <% room.get_room_accesories_count.map {|ra| %>
              <%= icon('fas',ra["icon"], class: ra["class"], "data-toggle" => "tooltip", "data-original-title" => ra["quantity"].to_s + " " + ra["name"], "data-placement" => "bottom") %>
              &nbsp;
              <% } %>
            </span>
            <hr />
            <span class="room_img">
              <%= image_tag("/logo_ibm_white.png") %><br />
              <span class="building_name"><%= room.building.name %> <%= room.floor %> floor</span>
            </span>
          </div>
          <% if current_user.is_admin? %>
          <table class="text-center w-100 table-borderedless">
            <tr>
              <td colspan="4">&nbsp;</td>
            </tr>
            <tr>
              <td>
                <% if room.active? %>
                <%= link_to room_path(room, "room[active]": '0'), method: :put, data: { confirm: room.name + ' is enabled, do you want to disable this room?' } do %>
                <%= icon('fas','ban', class: "text-danger", "data-toggle" => "tooltip", "data-original-title" => "Disable room", "data-placement" => "bottom") %>
                <% end %>
                <% else %>
                <%= link_to room_path(room, "room[active]": '1'), method: :put, data: { confirm: room.name + ' is disabled, do you want to enable this room?' } do %>
                <%= icon('fas','check-circle', class: "text-success", "data-toggle" => "tooltip", "data-original-title" => "Enable room", "data-placement" => "bottom") %>
                <% end %>
                <% end %>
              </td>
              <% if room.active? %>
              <td>
                <%= link_to new_booking_path(room_id: room.id) do %>
                <%= icon('fas', 'calendar-alt', class: "text-primary", "data-toggle" => "tooltip", "data-original-title" => "Book this room!", "data-placement" => "bottom") %>
                <% end %>
              </td>
              <% end %>
              <td>
                <%= link_to bookings_path(room_id: room.id) do %>
                <%= icon('fas', 'book-open', class: "text-info", "data-toggle" => "tooltip", "data-original-title" => "View room bookings", "data-placement" => "bottom") %>
                <% end %>
              </td>
              <td>
                <%= link_to edit_room_path(room) do %>
                <%= icon('fas', 'edit', class: "text-warning", "data-toggle" => "tooltip", "data-original-title" => "Edit room", "data-placement" => "bottom") %>
                <% end %>
              </td>
              <!-- Remove for enable delete
            <td>
              <%= link_to room, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <%= icon('fas', 'trash-alt', class: "text-danger", "data-toggle" => "tooltip", "data-original-title" => "Delete room", "data-placement" => "bottom") %>
              <% end %>
            </td>
            -->
            </tr>
          </table>
          <% end %>
      </div>
      <% if room.active? %>
      </a>
      <% end %>
      <% if current_user.is_admin? %>
    </div>
  </div>
  <% end %>

  <% i = i + 1 %>
  <%if (i % Kaminari.config.default_per_page) == 0 || i == @rooms.size %>
</div>
<% end %>
<% end %>

<br />

<div class="container pagination justify-content-center">
  <%= paginate @rooms, param_name: :pagina %>
</div>

<% if current_user.is_admin? %>

<div class="row mt-4 justify-content-md-center text-center">
  <div class="col-sm-3 m-1">
    <%= link_to 'Back', buildings_path, :class => "btn btn-outline-secondary btn-block"%>
  </div>
  <div class="col-sm-3 m-1">
    <%= link_to 'Create new room', new_room_path, :class => "btn btn-outline-success btn-block"%>
  </div>
</div>

<% else %>

<div class="row mt-4 justify-content-md-center text-center">
  <div class="col-sm-3 m-1">
    <%= link_to 'Back', buildings_path, :class => "btn btn-outline-secondary btn-block"%>
  </div>
<% if @title != "All rooms" %>
  <div class="col-sm-3 m-1">
    <%= link_to 'View all rooms', rooms_path, :class => "btn btn-outline-primary btn-block"%>
  </div>
<% end %>
</div>

<% end %>

app/views/rooms/new.html.erb
<h3>Add Room</h3>

<%= render 'form', room: @room, action: 'new' %>

app/views/rooms/real_state.html.erb
<h3>Room's state of real occupancy</h3>

<div id="div_info" style="display: none;"><i>The provided information is estimated.</i></div>

<div id="div_loading">
  <button class="btn btn-block btn-primary" type="button" disabled>
    Plase wait, collecting information from IoT ... <br />
    <span class="spinner-grow" style="width: 3rem; height: 3rem;" role="status" aria-hidden="true"></span>
    <br />Don't close this browser window ...
  </button>
</div>

<div class="row justify-content-md-center text-center" id="showData"></div>

<script>
  $.getJSON("/rooms/real_state.json").done(function (data) {
    var emptySet = true;
    $.each(data, function (key, room) {
      emptySet = false;

      var new_div = document.createElement("div");
      new_div.className = "col-sm-2 mt-1"
      new_div.innerHTML = '<div class="card text-center"><h5 class="card-header"><b>' + room.name + '</b></h5>' +
        '<div class="card-body centered">' +
        '<p>' + room.building + '</p>' +
        '<div class="progress" style="height: 15px;">' +
        '<div class="progress-bar bg-primary" role="progressbar" style="width: ' + room.used_percent + '%;" aria-valuenow="' + room.used_percent + '" aria-valuemin="0" aria-valuemax="100"></div>' +
        '</div>' +
        '<p>' + room.estimated_occupants + ' of ' + room.max_capacity + '</p>' +
        '<button class="btn btn-block btn-' + room.class + '" type="button" disabled>' +
        room.state +
        '</button>' +
        '</div>' +
        '</div>';
      $('#showData').append(new_div);
    })
    $('#div_loading').hide();
    if (emptySet) {
      $('#div_info').html('<p class="text-danger text-center">No available results</p>');
      $('#div_info').show();
    } else {
      $('#div_info').show();
    }
  });
</script>