config/routes.rb
Rails.application.routes.draw do

  resources :bookings, only: [:index, :show, :new, :create, :destroy]

  get '/rooms/real_state', to: 'rooms#real_state'
  get '/rooms/empty_with_booking', to: 'rooms#empty_with_booking'
  get '/rooms/busy_without_booking', to: 'rooms#busy_without_booking'

  resources :rooms
  resources :buildings
  resources :users

  get '/stats/top_five', to: 'stats#top_five'
  get '/stats/averages', to: 'stats#averages'
  get '/stats/rooms_bookings_by_day', to: 'stats#rooms_bookings_by_day'
  get '/stats/rooms_bookings_by_hour', to: 'stats#rooms_bookings_by_hour'

  root 'static_pages#home'
  get '/about', to: 'static_pages#about'

  get '/signup', to: 'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery width: :exception
  include SessionsHelper
  include ApplicationHelper
  before_action :logged_in_user
  skip_before_action :logged_in_user, only: [:new, :create, :home, :about]

  rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found

  def record_not_found
    flash[:danger] = 'The record was not found.'
    redirect_to root_url
  end

  def verify_if_admin_and_redirect_with_error_message_if_not
    unless logged_in? && current_user.is_admin?
      flash[:danger] = 'You are not authorized to perform that action'
      redirect_to root_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_alert_box.erb
<%= content_tag :div, class: "alert alert-#{message_type} alert-white rounded mb-3 fade show", id: "alert-general" do %>
<%= content_tag :div, class: "icon" do %>
<% if message_type == "danger" %>
<%= icon('fas', 'times-circle') %>
<% elsif message_type == "success" %>
<%= icon('fas', 'check-circle') %>
<% elsif message_type == "info" %>
<%= icon('fas', 'info-circle') %>
<% else %>
<%= icon('fas', 'exclamation-circle') %>
<% end %>
<% end %>
<%= sanitize(message) %>
<% end %>

<% if hide_alert %>
<script>
  setTimeout(function () { $("#alert-general").alert('close'); }, 3000);
</script>
<% end %>

app/views/application/_footer.html.erb
<footer class="footer bg-dark text-center">
  <div class="container">
    <span class="text-muted">IBM &copy; SmarterRooms - 2019</span>
  </div>
</footer>

app/views/application/_form_label.html.erb
<%
if defined?(add_class)
  add_class = ""
else
  add_class = "mb-3 row"
end
%>
<%= content_tag :div, class: "input-group " + add_class do %>
<%= content_tag :div, class: "input-group-prepend" do %>
<%= content_tag :span, class: "input-group-text" do %>
<%= icon('fas', fa_icon, class: 'fa-fw') %>
<% end %>
<% end %>
<%=
if !local_variables.include?(:max)
  max = 1000
end
case type
  when "text"
    form.text_field field, :required => required, placeholder: placeholder, class: "form-control"
  when "email"
    form.email_field field, :required => required, placeholder: placeholder, class: "form-control"
  when "password"
    form.password_field field, :required => required, placeholder: placeholder, class: "form-control", minlength: 8
  when "number"
    form.number_field field, :required => required, placeholder: placeholder, class: "form-control", step: :any, min: 1, max: max
  when "float"
    form.number_field field, :required => required, placeholder: placeholder, class: "form-control", step: "0.000001"
end
%>
<% end %>

app/views/application/_header.html.erb
<header>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <%= image_tag("/ibm_logo.png", size: "50x20") %>&nbsp;&nbsp;&nbsp;&nbsp;
    <a class="navbar-brand" href="/">SmarterRooms</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
      aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <% if !logged_in? %>
        <%= render partial: "navbar_not_logged" %>
        <% else %>
        <% if current_user.is_admin? %>
        <%= render partial: "navbar_admin_logged" %>
        <% else %>
        <%= render partial: "navbar_user_logged" %>
        <% end %>
        <% end %>
    </div>
  </nav>
</header>

app/views/application/_navbar_admin_logged.html.erb
<ul class="navbar-nav mr-auto">
  <li class="nav-item<%= ' active' if (controller_name == 'static_pages' || controller_name == 'sessions') && request.path != '/about' %>">
    <%= link_to '/', class: 'nav-link' do %>
    <%= icon('fas', 'home') %> Home
    <% end %>
  </li>
  <li
    class="nav-item<%= ' active' if (controller_name == 'users' && request.fullpath != '/users/' + current_user.id.to_s) %>">
    <%= link_to users_path, class: 'nav-link' do %>
    <%= icon('fas', 'users') %> Users
    <% end %>
  </li>
  <li class="nav-item<%= ' active' if controller_name == 'buildings' %>">
    <%= link_to buildings_path, class: 'nav-link' do %>
    <%= icon('fas', 'building') %> Sites
    <% end %>
  </li>
  <div class="dropdown show<%= ' active' if (controller_name == 'rooms') %>">
    <a class="btn dropdown-toggle" href="#" role="button" id="dropdownRoomsLink" data-toggle="dropdown"
      aria-haspopup="true" aria-expanded="false"
      <%= sanitize(' style="color: white;"') if controller_name == 'rooms' %></a> <i class="fas fa-door-open"></i>
      Rooms
    </a>

    <div class="dropdown-menu" aria-labelledby="dropdownRoomsLink">
      <%= link_to rooms_path, class: 'dropdown-item' do %>
      <%= icon('fas', 'door-closed') %> View all rooms
      <% end %>

      <%= link_to rooms_real_state_path, class: 'dropdown-item' do %>
      <%= icon('fas', 'chalkboard-teacher') %> State of real occupancy
      <% end %>

      <%= link_to rooms_empty_with_booking_path, class: 'dropdown-item' do %>
      <%= icon('fas', 'chalkboard') %> View empty rooms with active booking
      <% end %>

      <%= link_to rooms_busy_without_booking_path, class: 'dropdown-item' do %>
      <%= icon('fas', 'user-slash') %> View busy rooms without booking
      <% end %>
    </div>
  </div>
  <div class="dropdown show<%= ' active' if (controller_name == 'bookings') %>">
    <a class="btn dropdown-toggle" href="#" role="button" id="dropdownRoomsLink" data-toggle="dropdown"
      aria-haspopup="true" aria-expanded="false"
      <%= sanitize(' style="color: white;"') if controller_name == 'bookings' %></a> <i class="fas fa-book-open"></i>
      Bookings
    </a>

    <div class="dropdown-menu" aria-labelledby="dropdownRoomsLink">
      <%= link_to bookings_path(my_bookings: true), class: 'dropdown-item' do %>
      <%= icon('fas', 'user') %>&nbsp;&nbsp;&nbsp;My bookings
      <% end %>

      <%= link_to bookings_path, class: 'dropdown-item' do %>
      <%= icon('fas', 'users') %>&nbsp;&nbsp;All bookings
      <% end %>
    </div>
  </div>
  <div class="dropdown show<%= ' active' if (controller_name == 'stats') %>">
    <a class="btn dropdown-toggle" href="#" role="button" id="dropdownRoomsLink" data-toggle="dropdown"
      aria-haspopup="true" aria-expanded="false"
      <%= sanitize(' style="color: white;"') if controller_name == 'stats' %></a> <i class="fas fa-chart-bar"></i>
      Stats
    </a>

    <div class="dropdown-menu" aria-labelledby="dropdownRoomsLink">
      <%= link_to stats_top_five_path, class: 'dropdown-item' do %>
      <%= icon('fas', 'dice-five') %>&nbsp;&nbsp;Top five
      <% end %>

      <%= link_to stats_averages_path, class: 'dropdown-item' do %>
      <%= icon('fas', 'percent') %>&nbsp;&nbsp;Averages
      <% end %>
    </div>
  </div>
  <li class="nav-item<%= ' active' if request.fullpath == '/about' %>">
    <%= link_to about_path, class: 'nav-link' do %>
    <%= icon('fas', 'envelope') %> About
    <% end %>
  </li>
</ul>
<%= form_tag(rooms_path, method: :get, class: 'form-inline mt-2 mt-md-0') do %>
<%= text_field_tag :search_name, "", class: 'form-control mr-sm-2', placeholder: 'Find room by name ...' %>
<%= button_tag 'Search', class: 'btn btn-primary my-2 my-sm-0' %>
<% end %>

<div>&nbsp;</div>

<div
class="dropdown show<%= ' active' if (controller_name == 'users' && request.fullpath == '/users/' + current_user.id.to_s) %>">
<a class="btn dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
  aria-haspopup="true" aria-expanded="false"
  <%= sanitize(' style="color: white;"') if (controller_name == 'users' && request.fullpath == '/users/' + current_user.id.to_s) %></a>
  <i class="fas fa-user-circle"></i>
  <%= current_user.name %>
</a>

<div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
  <%= link_to edit_user_path(current_user), class: 'dropdown-item' do %>
  <%= icon('fas', 'user') %> My Profile
  <% end %>
  <%= link_to logout_path, method: 'delete', class: 'dropdown-item' do %>
  <%= icon('fas', 'sign-out-alt') %> Logout
  <% end %>
</div>
</div>

<div>&nbsp;</div>

app/views/application/_navbar_not_logged.html.erb
<ul class="navbar-nav mr-auto">
  <li class="nav-item<%= ' active' if request.fullpath == '/login' || request.fullpath == '/signup' %>">
    <%= link_to login_path, class: 'nav-link' do %>
    <%= icon('fas', 'sign-in-alt') %> Log in
    <% end %>
  </li>
  <li class="nav-item<%= ' active' if request.fullpath == '/about' %>">
    <%= link_to about_path, class: 'nav-link' do %>
    <%= icon('fas', 'envelope') %> About
    <% end %>
  </li>
</ul>

app/views/application/_navbar_user_logged.html.erb
<ul class="navbar-nav mr-auto">
    <li class="nav-item<%= ' active' if (controller_name == 'static_pages' || controller_name == 'sessions') && request.path != '/about' %>">
    <%= link_to '/', class: 'nav-link' do %>
    <%= icon('fas', 'home') %> Home
    <% end %>
  </li>
  <li class="nav-item<%= ' active' if controller_name == 'rooms' || controller_name == 'buildings' %>">
    <%= link_to buildings_path, class: 'nav-link' do %>
    <%= icon('fas', 'door-open') %> Rooms
    <% end %>
  </li>
  <li class="nav-item<%= ' active' if controller_name == 'bookings' %>">
    <%= link_to bookings_path, class: 'nav-link' do %>
    <%= icon('fas', 'book-open') %> My Bookings
    <% end %>
  </li>
  <li class="nav-item<%= ' active' if request.fullpath == '/about' %>">
    <%= link_to about_path, class: 'nav-link' do %>
    <%= icon('fas', 'envelope') %> About
    <% end %>
  </li>
</ul>
<%= form_tag(rooms_path, method: :get, class: 'form-inline mt-2 mt-md-0') do %>
<%= text_field_tag :search_name, "", class: 'form-control mr-sm-2', placeholder: 'Find room by name ...' %>
<%= button_tag 'Search', class: 'btn btn-primary my-2 my-sm-0' %>
<% end %>

<div>&nbsp;</div>

<div class="dropdown show<%= ' active' if controller_name == 'users' %>">
  <a class="btn dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
    aria-haspopup="true" aria-expanded="false"<%= sanitize(' style="color: white;"') if controller_name == 'users' %></a>
    <i class="fas fa-user-circle"></i>
    <%= current_user.name %>
  </a>

  <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
    <%= link_to edit_user_path(current_user), class: 'dropdown-item' do %>
    <%= icon('fas', 'user') %> My Profile
    <% end %>
    <%= link_to logout_path, method: 'delete', class: 'dropdown-item' do %>
    <%= icon('fas', 'sign-out-alt') %> Logout
    <% end %>
  </div>
</div>

<div>&nbsp;</div>